version: '2.3'

services:
  client:
    build:
      context: client
    volumes:
      - '/app/node_modules'
      - './client:/app'
    ports:
      - '8080:8080'
  server:
    build:
      context: serwer
    volumes:
      - './serwer:/usr/src/app'
    ports:
      - '5000:5000'
